# Generated by Django 4.2.7 on 2023-11-18 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_meeting_date_alter_meeting_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 18, 10, 44, 11, 991128)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2023, 11, 18, 10, 44, 11, 991128)),
        ),
    ]
